import { MusicRoom } from './types';

export const musicRooms: MusicRoom[] = [
  {
    id: 'listening-lounge',
    name: 'All Records',
    subtitle: 'The complete musical universe',
    description: 'The master collection containing every record, memory, and genre across the entire sanctuary.',
    theme: 'ambient-gold',
    icon: 'Disc3',
    ambientPreset: 'warm',
    tags: ['all', 'sanctuary', 'lounge'],
    order: 1,
    isVisible: true,
  },
  {
    id: 'pop',
    name: 'Pop / Contemporary',
    subtitle: '🌤️ Golden Hour • Romantic & Open',
    description: 'Accessible, romantic, mainstream love-song core. Golden hour daylight, soft sky, floating dust, and gentle movement.',
    theme: 'golden-hour',
    icon: 'Sun',
    ambientPreset: 'golden-pop',
    tags: ['pop', 'contemporary', 'romantic', 'golden-hour'],
    order: 2,
    isVisible: true,
  },
  {
    id: 'soft-rock',
    name: 'Soft Rock',
    subtitle: '💿 Vintage Room • Analog Devotion',
    description: 'Timeless, nostalgic, old-love-record feeling. Vintage lamps, wooden interiors, spinning vinyl, subtle film grain, and warm shadows.',
    theme: 'amber-wood',
    icon: 'Radio',
    ambientPreset: 'vintage-rock',
    tags: ['soft-rock', 'adult-contemporary', 'classic', 'timeless'],
    order: 3,
    isVisible: true,
  },
  {
    id: 'indie',
    name: 'Indie & Alt',
    subtitle: '🌿 Twilight Garden • Moonlight & Fireflies',
    description: 'Intimate, atmospheric, slightly unusual, and deeply personal. Twilight botanical garden, moonlight, plants, and bioluminescent fireflies.',
    theme: 'twilight-garden',
    icon: 'Sparkles',
    ambientPreset: 'twilight-indie',
    tags: ['indie', 'alternative', 'fireflies', 'atmospheric'],
    order: 4,
    isVisible: true,
  },
  {
    id: 'jazz',
    name: 'Jazz & Café',
    subtitle: '☕ Rainy Café • Coffee & Candles',
    description: 'The little late-night café universe. Intimate corner table, rain on window glass, candlelight, coffee steam, and Laufey jazz acoustics.',
    theme: 'cozy-cafe',
    icon: 'Coffee',
    ambientPreset: 'rainy-cafe',
    tags: ['jazz', 'bossa-nova', 'acoustic', 'cafe'],
    order: 5,
    isVisible: true,
  },
  {
    id: 'cinematic',
    name: 'Cinematic Romance',
    subtitle: '🎬 Dream Theater • Widescreen Stars',
    description: 'Songs that make an ordinary moment feel like a movie scene. Grand theater curtains, projector light rays, floating dust, and dramatic lens bloom.',
    theme: 'velvet-cinema',
    icon: 'Film',
    ambientPreset: 'dream-theater',
    tags: ['cinematic', 'epic', 'soundtrack', 'dramatic'],
    order: 6,
    isVisible: true,
  },
  {
    id: 'opm',
    name: 'Filipino / OPM',
    subtitle: '🇵🇭 Home at Night • Sincere Serenades',
    description: 'Closer to home. Familiar, intimate, unmistakably Filipino. Quiet balcony at night, warm window light, and enduring homegrown serenades.',
    theme: 'opm-warmth',
    icon: 'HeartHandshake',
    ambientPreset: 'home-opm',
    tags: ['opm', 'filipino', 'acoustic', 'sincere'],
    order: 7,
    isVisible: true,
  },
  {
    id: 'emo',
    name: '🖤 Emo & Pop-Punk',
    subtitle: '🌧️ Midnight Room • 2:00 AM Inner Monologue',
    description: 'Raw feelings, teenage nostalgia, relationship ache, longing, vulnerability, and songs that feel like they came directly from someone’s diary. Midnight rain, streetlights on wet pavement, dim desk lamp, and unspoken memories.',
    theme: 'midnight-emo',
    icon: 'Flame',
    ambientPreset: 'midnight-emo',
    tags: ['emo', 'pop-punk', 'alternative-rock', 'nostalgic', 'diary', 'ache'],
    order: 8,
    isVisible: true,
  },
];
